"""Add image column to Recipe model

Revision ID: 62513515cf47
Revises: 9368bd174c6f
Create Date: 2024-07-19 12:37:35.565820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62513515cf47'
down_revision = '9368bd174c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
